---
swagger: "2.0"
info:
  description: One Piece
  version: 1.0.0
  title: One Piece API
  contact:
    email: wbigger@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /wbigger/2022-5Binf-in-classe/1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /crews.json:
    get:
      tags:
      - developers
      summary: get all crews
      description: |
        Get all crews from database
      operationId: getCrews
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: return all crews with relative members
          schema:
            type: array
            items:
              $ref: '#/definitions/Crew'
        "400":
          description: bad input parameter
definitions:
  Pirate:
    type: object
    required:
    - age
    - id
    - name
    properties:
      id:
        type: integer
        format: int64
        example: 8
      name:
        type: string
        example: Roronoa Zoro
      age:
        type: integer
        format: int64
        example: 19
  Crew:
    type: object
    required:
    - id
    - name
    - pirates
    properties:
      id:
        type: integer
        format: int64
        example: 12
      name:
        type: string
        example: Hearth
      pirates:
        type: array
        items:
          $ref: '#/definitions/Pirate'
